name: goreleaser
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go
      
      - name: Run GoReleaser Build
        uses: goreleaser/goreleaser-action@v2
        if: github.event_name == 'push' && ! startsWith(github.ref, '/refs/tags')
        with:
          args: build
      
      - name: Run GoReleaser Release
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, '/refs/tags')
        with:
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}